# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.IpfpCoreC <- function(seed, target_list, target_data, print, iter, tol, na_target, n_threads = 1L) {
    .Call('_mipfp_IpfpCoreC', PACKAGE = 'mipfp', seed, target_list, target_data, print, iter, tol, na_target, n_threads)
}

